name: Sync Samples to S3 and CDN Invalidation

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "assets/docs/samples/**"

jobs:
  sync-samples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          curl -L -o /usr/local/bin/git-restore-mtime https://raw.githubusercontent.com/MestreLion/git-tools/master/git-restore-mtime
          chmod +x /usr/local/bin/git-restore-mtime

      - name: Restore file modification times from Git
        run: |
          git restore-mtime --no-directories assets/docs/samples
          find assets/docs/samples -type f -exec stat -c '%y %n' {} \; | sort

      - name: Sync assets/docs/samples to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 sync assets/docs/samples s3://static.teamlab.com/assets/docs/samples --acl public-read --delete

      - name: Invalidate CloudFront cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws cloudfront create-invalidation --distribution-id EK2IXZ2TWVZKC --paths "/assets/docs/samples/*"